[package]
name = "mayari/core"
version = "0.7.8"
description = "An Adaptive Luau Web Backend Framework."
authors = ["mayari-org"]
repository = "https://github.com/mayari-org/mayari"
license = "MIT"

[target]
environment = "luau"
main = ".mayari/src/index.luau"
includes = ["README.md", "LICENSE", ".mayari/src", "lpm.toml"]

[scripts]
"test" = "lute run test && lune run test && zune run test"
"format:check" = "stylua -c src/"
"format:fix" = "stylua src/"
"lint:check" = "selene src/"
res = "zune run resolve"

[tools]
lute = "luau-lang/lute@1.0.1-nightly.20260923"
lune = "lune-org/lune@0.10.5"
zune = "Scythe-Technology/zune@0.5.8"
stylua = "JohnnyMorganz/StyLua@2.5.2"
selene = "Kampfkarren/selene@0.31.0"
mayari-cli = "mayari-org/mayari-cli@0.1.3"

[dependencies]
common = { name = "mayari/common", version = "^" }
adpt = { name = "mayari/adpt", version = "^" }
types = { name = "mayari/types", version = "^" }
