name = "nova_guild/nova_core"
version = "0.5.7"
description = "A filesystem-based web framework for Luau runtimes, with out-of-the-box support for Lute, Lune and Zune."
authors = ["Nova Guild (https://github.com/nova-guild)"]
license = "MIT"
repository = "https://github.com/BizWiz3/nova"
private = false
includes =[
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**/*.luau",
]

[target]
environment = "luau"
lib = "src/index.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
